[package]
name = "solana-transaction-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
rand = "0.8.5"
ratatui = "0.28.1"
solana-client = "1.18.23"
solana-sdk = "1.18.23"
solana-transaction-status = "1.18.23"
tui-input = "0.10.1"
tui-menu = "0.2.4"
